### ISSUE TITLE
Does this still works? I get listening on 0.0.0.0:9339 but nothing happens

### ISSUE THREAD

**Issue by Gaspa79** [royale-proxy/cr-proxy#12]
Followed the instructions, patched the apk successfully, but the proxy is not receiving any data apparently and clash royale is not connecting =S. Tried using bluestacks and andyroid with the patched versions. Any ideas what I'm missing?

Thanks =)

**Comment by Asdamp** [comment]
0.0.0.0 is not a valid ip address. There is something wrong.

Il 23 lug 2017 18:05, "Gaspa79" <notifications@github.com> ha scritto:

**Comment by Gaspa79** [comment]
Yeah it is, it's the current machine. I accidentally opened the wrong CR for a second and messed everything up. Thanks a lot anyway!
