### ISSUE TITLE
I dont understand

### ISSUE THREAD

**Issue by Ermac889** [royale-proxy/cr-proxy#2]
Im kinda of a noob (I AM a noob) so i dont get too many terms so i was wondering if you could make a video about it please?

**Comment by mhsjlw** [comment]
This software (unfortunately!) isn't for you then. This repository contains code for learning about how the clash royale protocol works, and it **doesn't** contain any tools for creating custom servers or 'cheating' in the game, sorry (that's not to say that it won't happen in the future).
