### ISSUE TITLE
cr-messages-python dependency

### ISSUE THREAD

**Issue by hobbs** [royale-proxy/cr-proxy#5]
How do I install the cr-messages-python dependency? When I run this I get:

```
Traceback (most recent call last):
  File "proxy.py", line 2, in <module>
    from coc.message.definitions import CoCMessageDefinitions
ModuleNotFoundError: No module named 'coc.message.definitions'
```

Happy to update the README.md, just not familiar with python dep management.

**Comment by ghost** [comment]
Hey, try https://github.com/royale-proxy/cr-messages-python

**Comment by hobbs** [comment]
thanks @mhsjlw. how do I install that cr-messages-python package so cr-proxy can find it?

**Comment by srabouin** [comment]
Hey @mhsjlw sorry to hijack this but could you make me owner? I don't know where @akirarat is, hasn't been around for many weeks.

@hobbs install in the cr-proxy folder? should be in coc/messages and in there you should have cr-messages as definitions

**Comment by ghost** [comment]
Yup. You've got it
