### ISSUE TITLE
cr-patcher file not found error

### ISSUE THREAD

**Issue by ghost** [royale-proxy/cr-proxy#6]
Hi,

I'm new here, and would like to know what is happening.

Output:

`C:\Users\TJ\Documents\cr-patcher-master>python patcher.py 1.6.0`
`Getting config ...`
`Checking environment ...`
`Traceback (most recent call last):`
`File "patcher.py", line 147, in <module>`
`result = subprocess.run([config['paths']['keytool'], '-list', '-keystore', KEYSTORE_PATH, '-storepass', config['keystore']['storepass'], '-alias', config['keystore']['key']['alias']], stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)`
`File "C:\Users\TJ\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 693, in run`
`with Popen(*popenargs, **kwargs) as process:`
`File "C:\Users\TJ\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 947, in __init__`
`restore_signals, start_new_session)`
`File "C:\Users\TJ\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 1224, in _execute_child`
`startupinfo)`
`FileNotFoundError: [WinError 2] The system cannot find the file specified`

Attached is my config.json file in a .txt format.

[config.txt](https://github.com/royale-proxy/cr-proxy/files/737552/config.txt)

What am I doing wrong?

Thanks,

TJ  (PatmanDeuxMC)

**Comment by srabouin** [comment]
Probably the name of the apk file -- it should be com.supercell.clashroyale-1.x.x.apk

**Comment by ghost** [comment]
The file is named properly. I don't know what to do.

**Comment by ghost** [comment]
Bump :(

**Comment by srabouin** [comment]
You need to configure the path section, you're missing some stuff and make sure all is installed?

**Comment by ghost** [comment]
It is all installed... Just where DO I put Apktool and Zipalign?

**Comment by srabouin** [comment]
well mine looks like this:
"paths": {
    "apktool": "/usr/local/bin/apktool",
    "dd": "/bin/dd",
    "keytool": "/usr/bin/keytool",
    "jarsigner": "/usr/bin/jarsigner",
    "zipalign": "/Users/xx/Library/Android/sdk/build-tools/23.0.3/zipalign"
  }

**Comment by ghost** [comment]
Ok, but where are the directories located?

EDIT: Like, /usr/bin and stuff like that?

**Comment by srabouin** [comment]
Well you installed the software, so you should know where you installed when you clicked next next next -- don't know where they go in Windows, but should be easy to figure out on your own.

**Comment by ghost** [comment]
I really don't know!

**Comment by srabouin** [comment]
I'll ask in the chat and see if someone is on windows

**Comment by srabouin** [comment]
https://discord.gg/jQazFBz is the chat maybe someone else can help you

**Comment by ghost** [comment]
K thanks
