### ISSUE TITLE
1.8.2 Version ?

### ISSUE THREAD

**Issue by S1M0N38** [royale-proxy/cr-proxy#8]
Where I can find the Keys, Key Offsets and URL Offsets for 1.8.2 Version

**Comment by Galaxy1036** [comment]
Key for 1.8.2 are the same as 1.8.1

**Comment by erichegit** [comment]
What might be the problem if I get

ClientHello: {
  "protocol": 1,
  "keyVersion": 10,
  "majorVersion": 3,
  "minorVersion": 0,
  "build": 193,
  "contentHash": "f3df9782c358....",
  "deviceType": 2,
  "appStore": 2
}
ServerHello: {
  "sessionKey": "8ac12e14d017...."
}
**Failed to decrypt the message (server, 10101).**
connection from 192.168.1.x:53721 closed ...
connection to 54.190.22.27:9339 closed ...

**Comment by Galaxy1036** [comment]
It's because you use the original APK you need to patch one with cr-patcher

**Comment by erichegit** [comment]
thX - working fine.
Can you please explain why patching is so important?

With COC (when I was active) I always used the APK from the app store - it was only to know the encryption algorithm and the seed + key,...

**Comment by Galaxy1036** [comment]
Patching was important cuz the game use asymetric crypto protocol so if you wan't to decrypt packet you need the Supercell private key who is impossible to know. So we are using modded public key to use private modded key then we can decrypt all data (public key was in libg.so )
